### ISSUE TITLE
Crash on server start if masterMutationData.json or masterSeedData.json exist, but are empty

### ISSUE THREAD

**Issue by malcom2073** [jaredlll08/Fluxed-Crystals-Reborn#31]
As the title states, it crashes here https://github.com/jaredlll08/Fluxed-Crystals-Reborn/blob/master/src/main/java/fluxedCrystals/registry/MutationRegistry.java#L93 and here: https://github.com/jaredlll08/Fluxed-Crystals-Reborn/blob/master/src/main/java/fluxedCrystals/registry/SeedRegistry.java#L301

Looks like that particular JSON exception is not handled. Unsure _why_ the files were there but empty though... For what it's worth, I'm running this as part of Resonant Rise 3.2.7.2 server installation on an Ubuntu server. Let me know if there's anything else I can do.

Stacktrace for one of the two:

```
[08:06:05] [Server thread/INFO]: Starting minecraft server version 1.7.10
[08:07:10] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[JsonElement.class:?]
        at fluxedCrystals.registry.MutationRegistry.ReadFromDisk(MutationRegistry.java:93) ~[MutationRegistry.class:?]
        at fluxedCrystals.registry.MutationRegistry.Load(MutationRegistry.java:79) ~[MutationRegistry.class:?]
        at fluxedCrystals.FluxedCrystals.preInit(FluxedCrystals.java:78) ~[FluxedCrystals.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) ~[Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by ghost** [comment]
If you remove the empty files does it start up correctly?

The original design was that the mod would handle creating a default file if one didn't exist, however if a manual modification was made to the file the mod wouldn't touch it so that we didn't overwrite changes for a pack.

It sounds like someone left empty files kicking about, which unless there was another error that didn't get seen, someone had to manually edit the files into that state.  

I'll try to do a little digging on my end with that pack and see what is going on, I would start with removing the files and see if the mod recreates default files for you.

**Comment by jaredlll08** [comment]
Yea it is most likely that the files got corrupt, should be a pretty simple fix, in terms of checking the file, then recreating it.

**Comment by malcom2073** [comment]
Yep when I remove both files it starts fine and creates the default files as expected. 

I feel like an idiot, t totally forgot to mention that the server was improperly shut down, let me do that again and see if I can reproduce the error.

**Comment by ghost** [comment]
No worries, that can happen

**Comment by ghost** [comment]
Do keep in mind if the pack creator modified the files, the default ones we create won't match, so you will need to check against the files in the pack and make sure to capture any modifications they may have made.

**Comment by jaredlll08** [comment]
Hmm, yea that may be hard :/ I do know that RR doesn't edit the configs though.

**Comment by jaredlll08** [comment]
1.7 is no longer supported. 1.7.10 is 2 years / 4 versions old now, it is time to move on. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
